# https://taskfile.dev

version: "3"

vars:
  # Image registry.
  IMAGE_REGISTRY: localhost
  # Image repository
  IMAGE_REPOSITORY: pod-image-policy
  # Image tag. If not set, it defaults to a file hash, useful for local dev.
  IMAGE_TAG:
    sh: cat $(find . -name '*.go' -type f) go.mod Dockerfile | shasum | awk '{print substr($1,1,8)}'
  # Canonical image reference
  IMAGE_REFERENCE: "{{ .IMAGE_REGISTRY }}/{{ .IMAGE_REPOSITORY }}:{{ .IMAGE_TAG }}"

  KIND_CLUSTER:
    map:
      name: pod-image-policy
      cert_manager_version: v1.19.2

env:
  DOCKER_COMMAND: docker

tasks:
  build-image:
    desc: Build the application image
    internal: true
    status:
      - test -n "$($DOCKER_COMMAND images -q {{ .IMAGE_REFERENCE }})"
    cmd: $DOCKER_COMMAND build -t {{ .IMAGE_REFERENCE }} .

  ensure-cluster:
    desc: Ensure kind cluster exists and context is set
    internal: true
    run: once
    cmd: |-
      if kind get clusters | grep -q "{{ .KIND_CLUSTER.name }}"; then
        kubectl config use-context "kind-{{ .KIND_CLUSTER.name }}"
      else
        kind create cluster -n "{{ .KIND_CLUSTER.name }}"
      fi

  delete-cluster:
    desc: Delete kind cluster
    internal: true
    status:
      - '! kind get clusters | grep -q "{{ .KIND_CLUSTER.name }}"'
    cmd: kind delete cluster -n "{{ .KIND_CLUSTER.name }}"

  ensure-cert-manager:
    desc: Deploy cert-manager helm chart
    internal: true
    deps:
      - ensure-cluster
    status:
      - helm status cert-manager --namespace cert-manager
    cmd: >-
      helm install cert-manager oci://quay.io/jetstack/charts/cert-manager
      --version {{ .KIND_CLUSTER.cert_manager_version }}
      --namespace cert-manager
      --create-namespace
      --set crds.enabled=true

  load-image:
    desc: Load image into kind cluster
    internal: true
    deps:
      - ensure-cluster
      - build-image
    status:
      - test -n "$($DOCKER_COMMAND exec kind-{{ .KIND_CLUSTER.name }}-control-plane crictl images -q {{ .IMAGE_REFERENCE }})"
    cmds:
      - $DOCKER_COMMAND save {{ .IMAGE_REFERENCE }} -o /tmp/{{ .IMAGE_REPOSITORY }}-{{ .IMAGE_TAG }}.tar
      - kind load image-archive /tmp/{{ .IMAGE_REPOSITORY }}-{{ .IMAGE_TAG }}.tar --name {{ .KIND_CLUSTER.name }}

  deploy-chart:
    desc: Deploy the Helm chart to the kind cluster
    internal: true
    deps:
      - ensure-cluster
      - ensure-cert-manager
      - load-image
    cmd: >-
      helm upgrade pod-image-policy ./helm/pod-image-policy
      --install
      --namespace pod-image-policy
      --create-namespace
      --set image.repository=localhost/{{ .IMAGE_NAME }}
      --set image.tag={{ .IMAGE_HASH }}

  build:
    desc: Build the application image
    deps:
      - build-image

  local-deploy:
    desc: Deploy into local kind cluster
    deps:
      - deploy-chart

  format:
    desc: Format source code
    cmd: golangci-lint fmt {{ .CLI_ARGS }}

  check-format:
    desc: Check source code formatting
    cmd: golangci-lint fmt --diff {{ .CLI_ARGS }}

  lint:
    desc: Lint source code
    cmd: golangci-lint run {{ .CLI_ARGS }}

  test:
    desc: Run unit tests
    cmd: go test ./...
