apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pod-image-policy.fullname" . }}-webhook
  labels:
    {{- include "pod-image-policy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pod-image-policy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pod-image-policy.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pod-image-policy.serviceAccountName" . }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.args .Values.policy .Values.certManager.enabled }}
          args:
            {{- with .Values.args }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.policy }}
            - "-policyFile=/policy/policy.yaml"
            {{- end }}
            {{- if .Values.certManager.enabled }}
            - "-certFile=/tls/tls.crt"
            - "-keyFile=/tls/tls.key"
            {{- end }}
          {{- end }}
          ports:
            - name: https
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.policy }}
            - name: policy
              mountPath: /policy
              readOnly: true
            {{- end }}
            {{- if .Values.certManager.enabled }}
            - name: tls
              mountPath: /tls
              readOnly: true
            {{- end }}
            {{- if .Values.securityContext.readOnlyRootFilesystem }}
            - name: tmp
              mountPath: /tmp
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.policy }}
        - name: policy
          configMap:
            name: {{ include "pod-image-policy.fullname" . }}-policy
        {{- end }}
        {{- if .Values.certManager.enabled }}
        - name: tls
          secret:
            secretName: {{ include "pod-image-policy.fullname" . }}-webhook-tls
        {{- end }}
        {{- if .Values.securityContext.readOnlyRootFilesystem }}
        - name: tmp
          emptyDir: {}
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
