{{- if .Values.webhooks.mutating.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "pod-image-policy.fullname" . }}-mutating-webhook
  labels:
    {{- include "pod-image-policy.labels" . | nindent 4 }}
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "pod-image-policy.fullname" . }}-webhook-tls
  {{- end }}
webhooks:
  - name: {{ include "pod-image-policy.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
    admissionReviewVersions: {{ toYaml .Values.webhooks.mutating.admissionReviewVersions | nindent 4 }}
    sideEffects: {{ .Values.webhooks.mutating.sideEffects }}
    timeoutSeconds: {{ .Values.webhooks.mutating.timeoutSeconds }}
    failurePolicy: {{ .Values.webhooks.mutating.failurePolicy }}
    matchPolicy: {{ .Values.webhooks.mutating.matchPolicy }}
    {{- with .Values.webhooks.mutating.objectSelector }}
    objectSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.webhooks.mutating.namespaceSelector }}
    namespaceSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    rules:
      {{- toYaml .Values.webhooks.mutating.rules | nindent 6 }}
    clientConfig:
      service:
        name: {{ include "pod-image-policy.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: {{ .Values.webhooks.mutating.path }}
        {{- if .Values.webhooks.mutating.port }}
        port: {{ .Values.webhooks.mutating.port }}
        {{- else }}
        port: {{ .Values.service.port }}
        {{- end }}
      {{- with .Values.webhooks.mutating.caBundle }}
      caBundle: {{ . }}
      {{- end }}
{{- end }}
