{{- if .Values.policy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pod-image-policy.fullname" . }}-policy
  labels:
    {{- include "pod-image-policy.labels" . | nindent 4 }}
data:
  policy.yaml: |
{{ toYaml .Values.policy | indent 4 }}
{{- end }}
