{{- if .Values.webhook.mutating.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "pod-image-policy.fullname" . }}-mutating
  labels:
    {{- include "pod-image-policy.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "pod-image-policy.fullname" . }}.{{ .Release.Namespace }}.svc
    admissionReviewVersions: {{ toYaml .Values.webhook.mutating.admissionReviewVersions | nindent 4 }}
    sideEffects: {{ .Values.webhook.mutating.sideEffects }}
    timeoutSeconds: {{ .Values.webhook.mutating.timeoutSeconds }}
    failurePolicy: {{ .Values.webhook.mutating.failurePolicy }}
    matchPolicy: {{ .Values.webhook.mutating.matchPolicy }}
    {{- with .Values.webhook.mutating.objectSelector }}
    objectSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.webhook.mutating.namespaceSelector }}
    namespaceSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    rules:
      {{- toYaml .Values.webhook.mutating.rules | nindent 6 }}
    clientConfig:
      service:
        name: {{ include "pod-image-policy.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: {{ .Values.webhook.mutating.path }}
        {{- if .Values.webhook.mutating.port }}
        port: {{ .Values.webhook.mutating.port }}
        {{- else }}
        port: {{ .Values.service.port }}
        {{- end }}
      {{- with .Values.webhook.mutating.caBundle }}
      caBundle: {{ . }}
      {{- end }}
{{- end }}
